name: MediaMTX
version: "1.0.2"
hassio_api: true
homeassistant_api: true
slug: mediamtx
description: MediaMTX streaming server (RTSP / HLS / WebRTC)
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: true
map:
  - config:rw

options:
  mediamtx_config: |
    logLevel: info

    rtsp: yes
    rtspAddress: :8554

    hls: yes
    hlsAddress: :8888

    webrtc: yes
    webrtcAddress: :8889

    paths:
      all_others: {}

schema:
  mediamtx_config: str
