name: MediaMTX
version: "1.0.4"
hassio_api: true
homeassistant_api: true
slug: mediamtx
description: MediaMTX streaming server (RTSP / HLS / WebRTC)
arch:
  - amd64
  - aarch64
startup: services
boot: auto
map:
  - addon_config:rw

options:
  mediamtx_config: |
    logLevel: info

    rtsp: yes
    rtspAddress: :8554

    hls: yes
    hlsAddress: :8888

    webrtc: yes
    webrtcAddress: :8889

    paths:
      all_others: {}

ports:
  8554/tcp: 8554   # RTSP
  8888/tcp: 8888   # HLS (HTTP)
  8889/tcp: 8889   # WebRTC (HTTP signaling)

schema:
  mediamtx_config: str
